---
output: 
  pdf_document:
    keep_tex: yes
    fig_caption: yes
    number_sections: yes
geometry: margin=2.54cm
title: "Insert title of project here"
subtitle: "Web address for GitHub repository"
author: "Name"
fontsize: 12pt
mainfont: Times New Roman

---

\newpage

```{r setup, include=FALSE}
# Set your working directory
getwd()
# Load your packages
library(EcoHydRology)
library(tidyverse)
library(cowplot)
library(dataRetrieval)
library(lubridate)
library(lfstat)

# Set your ggplot theme
theme_set(theme_dark())
# Load your datasets

```


# Rationale and Research Questions
As we go out into a new world racked with climate change, we will encounter shifts in weather patterns with drastic consequences. As environmental managers we must be aware of alternate regimes and their potential consequences. To this end I am investigating effects of El Niño and La Niña on streams in Washington state. I will focus on discharge data to investigate potential effects on water supply throughout the year.

#Discharge displays effects of?

\newpage

# Dataset Information
Two data sources were required to address the research questions: discharge data and ENSO data indicating when El Niño and La Niña cycles were in effect. Discharge data was sourced from USGS Gage data through the dataRetrieval package. ENSO status was sourced from NOAA and processed through a script graciously provided by Dr. Luke Parsons. ENSO data is measured in Sea Surface Temperature (SST) in degrees Celsius. Any months with SST above 0.5°C were marked as under an El Niño cycle and all months below -0.5°C were marked as under a La Niña cycle, as per NOAA convention. 


\newpage

# Exploratory Analysis 
Visual inspection of discharge data, ENSO cycles, and their overlap informed my approach to statistical tests and data wrangling. As is immediately evident in Figure 1, ENSO cycles are not very evenly distributed. These classifications 


\newpage

# Analysis



## Question 1: Do El Nino/La Nina cycles affect discharge around Seattle?

## Question 2: What is the resolution of the effects?




\newpage

# Summary and Conclusions


\newpage

# References
<add references here if relevant, otherwise delete this section> 
