---
title: "Untitled"
author: "Sasha Keller"
date: "4/20/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# Set your working directory
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
# Set Output options
knitr::opts_chunk$set(echo=FALSE)
```

```{r}
library(tidyverse)
library(dataRetrieval)
library(maps)
library(sf)
# install.packages("nhdplusTools")
library(nhdplusTools)

theme_set(theme_classic())
options(scipen = 5)


```
```{r}
# Recall there are a lot of parameters measured at the site
DuckabushParams <- whatNWISdata(siteNumbers = "12054000")

# Extract latitude and longitude for the site
DuckabushCoords <- DuckabushParams %>%
  select(site_no, dec_lat_va, dec_long_va) %>%
  distinct()

# Define the gage site as the starting point
start_point <- st_sfc(st_point(c(DuckabushCoords$dec_long_va, DuckabushCoords$dec_lat_va)), 
                      crs = 4269) # NAD83, commonly  used by US agencies
start_comid <- discover_nhdplus_id(start_point)
# start_point2 <- st_as_sf(data.frame(x = NeuseCoords$dec_long_va, y =  NeuseCoords$dec_lat_va), 
#                             coords = c("x", "y"), crs = 4269)

# Navigate the NLDI network
NLDI <- navigate_nldi(list(featureSource = "comid", featureID = start_comid), 
                          mode = "upstreamTributaries", 
                          distance_km = 1000)

# Extract watershed and flowpath information
subset_file <- tempfile(fileext = ".gpkg")
subset <- subset_nhdplus(comids = as.integer(NLDI$UT$nhdplus_comid),
                         output_file = subset_file,
                         nhdplus_data = "download", 
                         flowline_only = FALSE,
                         return_data = TRUE, overwrite = TRUE)

# Create data frames
flowline1 <- subset$NHDFlowline_Network
catchment1 <- subset$CatchmentSP
waterbody <- subset$NHDWaterbody

# find gages near watershed
gages1 <- get_nwis(AOI = catchment1)
class(gages1)

# find gages only within watershed
gages1 <- st_intersection(gages1, catchment1)


plot_nhdplus("USGS-12054000", streamorder = 3)

states <- st_as_sf(map(database = "state", plot = FALSE, fill = TRUE, col = "white"))
wa <- filter(states, ID == "washington")

ggplot(wa) +
  geom_sf(fill = "white") +
  geom_sf(data = flowline1, aes(color = streamorde)) +
  labs(color = "Stream Order") +
  theme(legend.position = "top")

ggplot(catchment1) +
  geom_sf(fill = "white", color = "gray", lwd = 0.5) +
  geom_sf(data = flowline1, aes(color = streamorde)) +
  geom_sf(data = gages1, color = "darkred", size = 1) +
  labs(color = "Stream Order") +
  theme(legend.position = "top")


```


```{r}
# Recall there are a lot of parameters measured at the site
TulalipParams <- whatNWISdata(siteNumbers = "12158040")

# Extract latitude and longitude for the site
TulalipCoords <- TulalipParams %>%
  select(site_no, dec_lat_va, dec_long_va) %>%
  distinct()

# Define the gage site as the starting point
start_point <- st_sfc(st_point(c(TulalipCoords$dec_long_va, TulalipCoords$dec_lat_va)), 
                      crs = 4269) # NAD83, commonly  used by US agencies
start_comid <- discover_nhdplus_id(start_point)
# start_point2 <- st_as_sf(data.frame(x = NeuseCoords$dec_long_va, y =  NeuseCoords$dec_lat_va), 
#                             coords = c("x", "y"), crs = 4269)

# Navigate the NLDI network
NLDI <- navigate_nldi(list(featureSource = "comid", featureID = start_comid), 
                          mode = "upstreamTributaries", 
                          distance_km = 1000)

# Extract watershed and flowpath information
subset_file <- tempfile(fileext = ".gpkg")
subset <- subset_nhdplus(comids = as.integer(NLDI$UT$nhdplus_comid),
                         output_file = subset_file,
                         nhdplus_data = "download", 
                         flowline_only = FALSE,
                         return_data = TRUE, overwrite = TRUE)

# Create data frames
flowline2 <- subset$NHDFlowline_Network
catchment2 <- subset$CatchmentSP
waterbody <- subset$NHDWaterbody

# find gages near watershed
gages2 <- get_nwis(AOI = catchment2)
class(gages2)

# find gages only within watershed
gages2 <- st_intersection(gages2, catchment2)


#plot_nhdplus("USGS-12158040", streamorder = 3)

states <- st_as_sf(map(database = "state", plot = FALSE, fill = TRUE, col = "white"))
wa <- filter(states, ID == "washington")

ggplot(wa) +
  geom_sf(fill = "white") +
  geom_sf(data = flowline2, aes(color = streamorde)) +
  labs(color = "Stream Order") +
  theme(legend.position = "top")

ggplot(catchment2) +
  geom_sf(fill = "white", color = "gray", lwd = 0.5) +
  geom_sf(data = flowline2, aes(color = streamorde)) +
  geom_sf(data = gages2, color = "darkred", size = 1) +
  labs(color = "Stream Order") +
  theme(legend.position = "top")

```

```{r}
# Recall there are a lot of parameters measured at the site
SkokomishParams <- whatNWISdata(siteNumbers = "12061500")

# Extract latitude and longitude for the site
SkokomishCoords <- SkokomishParams %>%
  select(site_no, dec_lat_va, dec_long_va) %>%
  distinct()

# Define the gage site as the starting point
start_point <- st_sfc(st_point(c(SkokomishCoords$dec_long_va, SkokomishCoords$dec_lat_va)), 
                      crs = 4269) # NAD83, commonly  used by US agencies
start_comid <- discover_nhdplus_id(start_point)
# start_point2 <- st_as_sf(data.frame(x = NeuseCoords$dec_long_va, y =  NeuseCoords$dec_lat_va), 
#                             coords = c("x", "y"), crs = 4269)

# Navigate the NLDI network
NLDI <- navigate_nldi(list(featureSource = "comid", featureID = start_comid), 
                          mode = "upstreamTributaries", 
                          distance_km = 1000)

# Extract watershed and flowpath information
subset_file <- tempfile(fileext = ".gpkg")
subset <- subset_nhdplus(comids = as.integer(NLDI$UT$nhdplus_comid),
                         output_file = subset_file,
                         nhdplus_data = "download", 
                         flowline_only = FALSE,
                         return_data = TRUE, overwrite = TRUE)

# Create data frames
flowline3 <- subset$NHDFlowline_Network
catchment3 <- subset$CatchmentSP
waterbody <- subset$NHDWaterbody

# find gages near watershed
gages3 <- get_nwis(AOI = catchment3)
class(gages3)

# find gages only within watershed
gages3 <- st_intersection(gages3, catchment3)


plot_nhdplus("USGS-12061500", streamorder = 3)

states <- st_as_sf(map(database = "state", plot = FALSE, fill = TRUE, col = "white"))
wa <- filter(states, ID == "washington")

ggplot(wa) +
  geom_sf(fill = "white") +
  geom_sf(data = flowline3, aes(color = streamorde)) +
  labs(color = "Stream Order") +
  theme(legend.position = "top")

ggplot(catchment3) +
  geom_sf(fill = "white", color = "gray", lwd = 0.5) +
  geom_sf(data = flowline3, aes(color = streamorde)) +
  geom_sf(data = gages3, color = "darkred", size = 1) +
  labs(color = "Stream Order") +
  theme(legend.position = "top")



```

```{r}
# Recall there are a lot of parameters measured at the site
PuyallupParams <- whatNWISdata(siteNumbers = "12101500")

# Extract latitude and longitude for the site
PuyallupCoords <- PuyallupParams %>%
  select(site_no, dec_lat_va, dec_long_va) %>%
  distinct()

# Define the gage site as the starting point
start_point <- st_sfc(st_point(c(PuyallupCoords$dec_long_va, PuyallupCoords$dec_lat_va)), 
                      crs = 4269) # NAD83, commonly  used by US agencies
start_comid <- discover_nhdplus_id(start_point)
# start_point2 <- st_as_sf(data.frame(x = NeuseCoords$dec_long_va, y =  NeuseCoords$dec_lat_va), 
#                             coords = c("x", "y"), crs = 4269)

# Navigate the NLDI network
NLDI <- navigate_nldi(list(featureSource = "comid", featureID = start_comid), 
                          mode = "upstreamTributaries", 
                          distance_km = 1000)

# Extract watershed and flowpath information
subset_file <- tempfile(fileext = ".gpkg")
subset <- subset_nhdplus(comids = as.integer(NLDI$UT$nhdplus_comid),
                         output_file = subset_file,
                         nhdplus_data = "download", 
                         flowline_only = FALSE,
                         return_data = TRUE, overwrite = TRUE)

# Create data frames
flowline4 <- subset$NHDFlowline_Network
catchment4 <- subset$CatchmentSP
waterbody <- subset$NHDWaterbody

# find gages near watershed
gages4 <- get_nwis(AOI = catchment4)
class(gages4)

# find gages only within watershed
gages4 <- st_intersection(gages4, catchment4)


plot_nhdplus("USGS-12101500", streamorder = 3)

states <- st_as_sf(map(database = "state", plot = FALSE, fill = TRUE, col = "white"))
wa <- filter(states, ID == "washington")

ggplot(wa) +
  geom_sf(fill = "white") +
  geom_sf(data = flowline4, aes(color = streamorde)) +
  labs(color = "Stream Order") +
  theme(legend.position = "top")

ggplot(catchment4) +
  geom_sf(fill = "white", color = "gray", lwd = 0.5) +
  geom_sf(data = flowline4, aes(color = streamorde)) +
  geom_sf(data = gages4, color = "darkred", size = 1) +
  labs(color = "Stream Order") +
  theme(legend.position = "top")



```

```{r}
ggplot(wa) +
  geom_sf(fill = "white") +
  geom_sf(data = flowline1, aes(color = streamorde)) +
    geom_sf(data = flowline2, aes(color = streamorde)) +
    geom_sf(data = flowline3, aes(color = streamorde)) +
    geom_sf(data = flowline4, aes(color = streamorde)) +
  coord_sf(xlim = c(-123.6, -121.2), ylim = c(46.5, 48.5), expand = FALSE)+
  labs(color = "Stream Order") +
  theme(legend.position = "top")

```